sugarcube-2:
  macros:
    dialog:
      name: dialog
      container: true
    date:
      name: date
    time12hr:
      name: time12hr
    leave:
      name: leave
    passage:
      name: passage
    dialogclose:
      name: dialogclose
    time24hr:
      name: time24hr
    ibutton:
      name: ibutton
      container: true
    gotobutton:
      name: gotobutton
      container: true
    dialoguebutton:
      name: dialoguebutton
      container: true
    removebutton:
      name: removebutton
      container: true
